(function(){
    [...document.querySelectorAll(".control")].forEach(button=>{
        button.addEventListener('click',function(){
            document.querySelector('.btn_active').classList.remove('btn_active');
            this.classList.add('btn_active');
            document.querySelector('.active').classList.remove('active');
            document.getElementById(button.dataset.id).classList.add('active'); 
        })
    })
})();